# travis config checker: http://config.travis-ci.org/

language: cpp

git:
  depth: false

before_install: git fetch --tags

stages:
  - test
  - deploy

env:
  global:
    - CMAKE_BUILD_TYPE=Release

matrix:
  include:
  # Docker
  - &centos-7-template
    name: "CentOS Docker"
    stage: test
    os: linux
    services:
      - docker
    install: .travis/docker/install_deps.sh
    before_script: source .travis/docker/before_build.sh
    script: .travis/docker/build.sh

  - <<: *centos-7-template
    name: "CentOS Docker - Deploy"
    stage: deploy
    deploy:
      provider: script
      script: .travis/docker/deploy.sh
      on:
        branch: master

  - &opensuse-template
    name: "OpenSUSE Leap Docker"
    #env: CXX=/usr/bin/cpp CXX_COMPILER=/usr/bin/cpp CMAKE_CXX_COMPILER=/usr/bin/cpp
    stage: test
    os: linux
    services:
      - docker
    install: .travis/opensuse/install_deps.sh
    before_script: source .travis/opensuse/before_build.sh
    script: .travis/opensuse/build.sh
