lannguage: python

services:
- docker

before_install:
- docker pull ldumas/sirius_dockerfile:sirius_build
- docker pull ldumas/sirius_dockerfile:sirius_pages

before_script:
- echo $TRAVIS_PULL_REQUEST
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export SRCDIR=/data

script:
- docker run -v $TRAVIS_BUILD_DIR/:/data ldumas/sirius_dockerfile:sirius_build /bin/sh -c "source /opt/rh/devtoolset-6/enable; cd $SRCDIR; [ ! -d .build ] && mkdir .build; cd .build; cmake3 .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/sirius -DENABLE_CACHE_OPTIMIZATION=ON -DENABLE_GSL_CONTRACTS=OFF -DENABLE_LOGS=ON -DENABLE_UNIT_TESTS=OFF -DENABLE_DOCUMENTATION=ON; make && make install; rm -rf .build"
- CID=$(docker ps --latest --quiet)
- docker commit --change "ENV PATH $PATH:/opt/sirius/bin" $CID sirius_built
- docker tag sirius_built ldumas/sirius_dockerfile:sirius_built
- docker push ldumas/sirius_dockerfile:sirius_built

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: develop

after_success:
- .travis/on_success.sh
