# travis config checker: http://config.travis-ci.org/

language: cpp

git:
  depth: false

before_install: git fetch --tags

stages:
  - test
  - deploy

env:
  global:
    - CMAKE_BUILD_TYPE=Release

matrix:
  include:
  # OS X
  - &osx-template
    stage: test
    name: "OS X - Xcode 8.3"
    os: osx
    osx_image: xcode8.3
    install: .travis/osx/install_deps.sh
    before_script: source .travis/osx/before_build.sh
    script: .travis/osx/build.sh

  - <<: *osx-template
    name: "OS X - Xcode 9.4"
    osx_image: xcode9.4

  - <<: *osx-template
    name: "OS X - Xcode 10.3"
    osx_image: xcode10.3

  - <<: *osx-template
    name: "OS X - Xcode 11.3"
    osx_image: xcode11.3

  # Ubuntu xenial
  - &ubuntu-xenial-template
    stage: test
    name: "Ubuntu Xenial 16.04 GCC 6"
    os: linux
    dist: xenial
    before_script: source .travis/linux/before_build.sh
    script: .travis/linux/build.sh
    env: CXX_COMPILER=/usr/bin/g++-6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - g++-6
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-xenial-template
    name: "Ubuntu Xenial 16.04 GCC 6 - C++ static runtime"
    env: CXX_COMPILER=/usr/bin/g++-6 USE_CXX_STATIC_RUNTIME=ON
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - g++-6
          - libfftw3-dev
          - libgdal-dev

  # Ubuntu bionic
  - &ubuntu-bionic-template
    stage: test
    name: "Ubuntu Bionic 18.04 GCC 7 - C++"
    os: linux
    dist: bionic
    before_script: source .travis/linux/before_build.sh
    script: .travis/linux/build.sh
    env: CXX_COMPILER=/usr/bin/g++-7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - g++-7
          - libfftw3-dev
          - libgdal-dev

  - <<: *ubuntu-bionic-template
    name: "Ubuntu Bionic 18.04 GCC 7 - C++ static runtime"
    env: CXX_COMPILER=/usr/bin/g++-7 USE_CXX_STATIC_RUNTIME=ON
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - g++-7
          - libfftw3-dev
          - libgdal-dev

  # Docker
  - &centos-7-template
    name: "CentOS Docker"
    stage: test
    os: linux
    services:
      - docker
    install: .travis/docker/install_deps.sh
    before_script: source .travis/docker/before_build.sh
    script: .travis/docker/build.sh

  - <<: *centos-7-template
    name: "CentOS Docker - Deploy"
    stage: deploy
    deploy:
      provider: script
      script: .travis/docker/deploy.sh
      on:
        branch: master
