services:
- docker

before_install:
- docker pull ldumas/sirius_dockerfile:sirius_build
- docker pull ldumas/sirius_dockerfile:sirius_pages

before_script:
- if [ "x${TRAVIS_PULL_REQUEST}" = "xfalse" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; fi
- export SRCDIR=/data

script:
- docker run -v $TRAVIS_BUILD_DIR/:/data ldumas/sirius_dockerfile:sirius_build /bin/sh -c "source /opt/rh/devtoolset-6/enable; cd $SRCDIR; [ ! -d .build ] && mkdir .build; cd .build; cmake3 .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/sirius -DENABLE_CACHE_OPTIMIZATION=ON -DENABLE_GSL_CONTRACTS=OFF -DENABLE_LOGS=ON -DENABLE_UNIT_TESTS=OFF -DENABLE_DOCUMENTATION=ON; make && make install; cd ..; mv .build/html doxy_html; rm -rf .build"
- CID=$(docker ps --latest --quiet)
- if [ "x${TRAVIS_PULL_REQUEST}" = "xfalse" ]; then docker commit --change "ENV PATH $PATH:/opt/sirius/bin" $CID sirius_built; fi
- if [ "x${TRAVIS_PULL_REQUEST}" = "xfalse" ]; then docker tag sirius_built ldumas/sirius_dockerfile:sirius_built; fi
- if [ "x${TRAVIS_PULL_REQUEST}" = "xfalse" ]; then docker push ldumas/sirius_dockerfile:sirius_built; fi

deploy:
  provider: script
  script: if [ "x${TRAVIS_PULL_REQUEST}" = "xfalse" ]; then .travis/deploy.sh; fi
  on:
    branch: master

after_success:
- if [ "x${TRAVIS_PULL_REQUEST}" = "xfalse" ]; then .travis/on_success.sh; fi
