services:
- docker

git:
  depth: false

before_install:
- docker pull ldumas/sirius_dockerfile:sirius_build
- docker pull ldumas/sirius_dockerfile:sirius_pages

before_script:
- export SRCDIR=/data
- export SIRIUS_BUILD_DIR=.build
- export INSTALL_DIR=/opt/sirius
- SIRIUS_VERSION=$(git describe 2> /dev/null); if [ "x${SIRIUS_VERSION}" = "x" ]; then SIRIUS_VERSION="0.0.0"; fi; export SIRIUS_VERSION;

script:
- docker run -v $TRAVIS_BUILD_DIR/:/data ldumas/sirius_dockerfile:sirius_build /bin/sh -c "source /opt/rh/devtoolset-6/enable; ${SRCDIR}/.travis/build_install_sirius.sh ${SRCDIR} ${INSTALL_DIR} ${SIRIUS_VERSION} ${TRAVIS_COMMIT}"
- export BUILD_CONTAINER_ID=$(docker ps --latest --quiet)

after_success:
- .travis/on_success.sh

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
